INPUT_PATHS="Dataset_Edge\\Edges_img"
TARGET_PATHS="Dataset_Edge\\Real_img"
PREDICT_PATHS="Predict_img"
TENSORBOARD_PATH="Tensorboard"
SAVE_CHECKPOINT_PATH="pix2pix_check.pth.tar"

VALID_SIZE=10000
BATCH_SIZE=10

CHANNEL_SIZE_INPUT=1
CHANNEL_SIZE_OUTPUT=3

EPOCHS=10
LEARNING_RATE=5e-4
BETAS=(0.5,0.999)
LAMDA_L1=100

MAX_BATCH_TRAIN=300
MAX_BATCH_TEST=50

LOAD_CHECKPOINTS=False
PREDICTIONS=True
TEST=True
TRAIN=True

